from tkinter import *
import random
from tkinter import messagebox

# Create a window
root = Tk()
root.geometry("600x500")
root.title('Lotto App')
root.configure(background='#3E464A')


# function to open this module
def popup():
    pass


# Headings & labels on top of the window
heading = Label(root, text="NOW LET'S PLAY", font='arial 20 bold', fg='white', bg='#3E464A')
heading.pack(pady=10)
heading1 = Label(root, text='Please enter your 6 lucky numbers accordingly.', font='arial 13 bold', fg='white',
                 bg='#3E464A')
heading.pack(pady=20)

# Entries by Player has to be An Integer
num1 = IntVar()
num2 = IntVar()
num3 = IntVar()
num4 = IntVar()
num5 = IntVar()
num6 = IntVar()

# Frame to place the Entries by Player
entrie_frame = Frame(root)
entrie_frame.pack(pady=15)

# Player Entry boxes for predicted numbers
txt1 = Entry(entrie_frame, textvariable=num1, font='arial 15 bold', width=4)
txt1.pack(side=RIGHT, padx=5, pady=5)
txt2 = Entry(entrie_frame, textvariable=num2, font='arial 15 bold', width=4)
txt2.pack(side=RIGHT, padx=5, pady=5)
txt3 = Entry(entrie_frame, textvariable=num3, font='arial 15 bold', width=4)
txt3.pack(side=RIGHT, padx=5, pady=5)
txt4 = Entry(entrie_frame, textvariable=num4, font='arial 15 bold', width=4)
txt4.pack(side=RIGHT, padx=5, pady=5)
txt5 = Entry(entrie_frame, textvariable=num5, font='arial 15 bold', width=4)
txt5.pack(side=RIGHT, padx=5, pady=5)
txt6 = Entry(entrie_frame, textvariable=num6, font='arial 15 bold', width=4)
txt6.pack(side=RIGHT, padx=5, pady=5)


# Generating function, Comparison between entries & generated numbers & displaying output to the player
def luck():
    # Getting the entries by the player
    x = num1.get()
    y = num2.get()
    z = num3.get()
    a = num4.get()
    b = num5.get()
    c = num6.get()

    # Sorting the entries by player
    my_list = [x, y, z, a, b, c]
    my_list.sort()

    # Sorting the lotto random numbers generated by my app
    lotto_nums = sorted(random.sample(range(1, 49), 6))

    # Show a pop up messagebox to get ready to play
    if any(my_list) < 0 or any(my_list) < 50:
        messagebox.showinfo("GAME TIME", "Get ready Player!!")

    # Function to compare Entry numbers with the Generated numbers & display a message
    if len(lotto_nums) == len(my_list):
        same = set(lotto_nums).intersection(set(my_list))
    if len(same) == 6:
        result_answer.config(
            text="YOU WON A JACKPOT!!! \n"
                 + "R10,000 000,00 in Prizes!\n"
                 + "Lotto Numbers Today are\n"
                 + str(lotto_nums))

    elif len(same) == 5:
        result_answer.config(
            text="HATS OFF TO YOU BOSS!!\n"
                 + "You got 5 numbers correct\n"
                 + "With this Outstanding Achievement\n"
                 + "You won yourself R8,584,00\n"
                 + "Lotto Numbers Today are\n"
                 + str(lotto_nums))

    elif len(same) == 4:
        result_answer.config(
            text="Congratulations and BRAVO!!\n"
                 + "- You got 4 numbers correct -\n"
                 + "I knew it was only a matter of time. Well done!\n"
                 + "You won yourself R2,384.00\n"
                 + "Today Lotto Numbers are\n"
                 + str(lotto_nums))

    elif len(same) == 3:
        result_answer.config(
            text="CONGRATS YOU GOT HALF THE NUMBERS!!\n"
                 + "You got 3 numbers correct\n"
                 + "With this Substantial Achievement\n"
                 + "You won R100.50\n"
                 + "Today Lotto Numbers are\n"
                 + str(lotto_nums))

    elif len(same) == 2:
        result_answer.config(
            text=" CONGRATS!! \n"
                 + "You got 2 numbers correct\n"
                 + "With this Adequate Achievement\n"
                 + "YOU WON R 20,00 \n"
                 + "Today Lotto Numbers are\n"
                 + str(lotto_nums))

    elif len(same) == 1:
        messagebox.showinfo("RESULT",
                            "We are sorry you only got one correct lotto numbers are: "
                            + str(lotto_nums))
    elif len(same) == 0:
        messagebox.showinfo("RESULT",
                            "LIFE ALWAYS OFFERS YOU A SECOND CHANCE.\n"
                            "IT'S CALLED TOMORROW\n"
                            "Try again Lotto numbers were: \n"
                            + str(lotto_nums))
    else:
        messagebox.showinfo("NOOO", "Follow the rules")
        num1.delete(0, END)
        num2.delete(0, END)
        num3.delete(0, END)
        num4.delete(0, END)
        num5.delete(0, END)
        num6.delete(0, END)


# Button to run the app to generate & compare number by Player with the Generated
btn = Button(root, text="RUN RESULTS", bg="#f2c831", command=luck)
btn.pack(pady=15)

# LAbel to display results
result_answer = Label(root, width=50, height=8)
result_answer.pack(pady=15)


# Function to close app(Close App) Button
def close():
    root.destroy()


# Close App
btn = Button(root, text="Close App", bg="#f2c831", command=close)
btn.pack()
# Closing my window
root.mainloop()
